-- The four tables Meetings owns, in its own schema.
--
-- Generated by `pnpm db:generate` from `src/server/schema.ts` and then guarded by hand, because
-- drizzle-kit 0.31 emits bare `CREATE SCHEMA`, `CREATE TABLE` and `CREATE INDEX`. **Every statement
-- in this folder has to survive being run twice.** A module's migrations are the first thing the
-- kernel runs, so one that throws does not degrade its own feature — it stops the host service
-- binding its port and takes every other module in that service down with it. A replay is not
-- hypothetical either: drizzle keys applied migrations by content hash, so editing any file in this
-- folder makes the whole folder run again against schemas that already have their objects.
--
-- `create schema if not exists` matters on its own: the kernel creates `mod_meet` before running
-- these, so the bare form fails on the very first boot.
--
-- Note the half of idempotence that has no guard: a replayed `create table if not exists` reports
-- success and changes nothing. So *rewriting* a file here leaves an existing schema exactly as it
-- was, silently — the boot failure disappears and the change never happens. After anything depends
-- on this data, a change is a new migration, never an edit to this one.
--
-- The two `check` constraints sit **inside** `create table`, where they inherit its guard. As a
-- separate `alter table … add constraint` they would need a `drop constraint if exists` in front of
-- each, which is the shape `0001_rls.sql` uses for the things that cannot be written inline.

CREATE SCHEMA IF NOT EXISTS "mod_meet";
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_meet"."invites" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"meeting_id" uuid NOT NULL,
	"from_user_id" uuid NOT NULL,
	"to_user_id" uuid NOT NULL,
	"state" text DEFAULT 'ringing' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "meet_invites_state_ck" CHECK ("mod_meet"."invites"."state" in ('ringing','answered','declined','cancelled','missed'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_meet"."meetings" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"livekit_room" text NOT NULL,
	"room_id" uuid,
	"object_module" text,
	"object_type" text,
	"object_id" text,
	"title" text,
	"started_by" uuid NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"ended_reason" text,
	"peak_participants" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "meet_meetings_kind_ck" CHECK ("mod_meet"."meetings"."kind" in ('direct','huddle','room')),
	CONSTRAINT "meet_meetings_ended_reason_ck" CHECK ("mod_meet"."meetings"."ended_reason" is null or "mod_meet"."meetings"."ended_reason" in ('empty','ended_by_host','reconciled','expired'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_meet"."participants" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"meeting_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"left_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mod_meet"."rooms" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"created_by" uuid,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "meet_invites_meeting_user_uq" ON "mod_meet"."invites" USING btree ("meeting_id","to_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_invites_ws_to_state_idx" ON "mod_meet"."invites" USING btree ("workspace_id","to_user_id","state");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_invites_expiry_idx" ON "mod_meet"."invites" USING btree ("state","expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "meet_meetings_livekit_room_uq" ON "mod_meet"."meetings" USING btree ("livekit_room");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "meet_meetings_room_live_uq" ON "mod_meet"."meetings" USING btree ("room_id") WHERE ended_at is null and room_id is not null;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "meet_meetings_object_live_uq" ON "mod_meet"."meetings" USING btree ("workspace_id","object_module","object_type","object_id") WHERE ended_at is null and object_id is not null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_meetings_ws_started_idx" ON "mod_meet"."meetings" USING btree ("workspace_id","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_meetings_ws_live_idx" ON "mod_meet"."meetings" USING btree ("workspace_id") WHERE ended_at is null;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "meet_participants_live_uq" ON "mod_meet"."participants" USING btree ("meeting_id","user_id") WHERE left_at is null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_participants_ws_meeting_idx" ON "mod_meet"."participants" USING btree ("workspace_id","meeting_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_participants_ws_user_idx" ON "mod_meet"."participants" USING btree ("workspace_id","user_id","joined_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "meet_rooms_ws_slug_uq" ON "mod_meet"."rooms" USING btree ("workspace_id","slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meet_rooms_ws_idx" ON "mod_meet"."rooms" USING btree ("workspace_id","name");
